### ISSUE TITLE
Is there a way to use SublimeLinter happiness with ES2015?

### ISSUE THREAD

**Issue by corysimmons** [nmn/SublimeLinter-contrib-happiness#1]
![image](https://cloud.githubusercontent.com/assets/224636/13028493/a5fedcfe-d23e-11e5-9524-39b68fee8e15.png)

I'm pretty sure I'm adhering to happiness but it's picking up the ES2015 as errors. :(

**Comment by nmn** [comment]
This plugin pretty much hands-off all the work to the nam module. Find out if the the CLI gives you the same errors.

If so, this Issue should be moved to the the Happiness repo.

**Comment by corysimmons** [comment]
Alright thanks. :+1:
